In [1]:
import pandas as pd
import re

In [2]:
f=open("whats app data/WhatsApp Chat with Subhojit.txt","r",encoding="utf-8")

In [3]:
data=f.read()

In [4]:
print(data)

01/01/25, 7:07 pm - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
19/01/25, 8:58 am - ᗩʏᴏɴ ×͜×: Vai tui svmcm ar print out college a joma diechilis?
19/01/25, 9:28 am - Subhojit: Gechilam
19/01/25, 9:28 am - Subhojit: Joma nayni
19/01/25, 9:28 am - Subhojit: Tor dhukeche???
19/01/25, 9:28 am - ᗩʏᴏɴ ×͜×: Na vai
19/01/25, 10:09 am - Subhojit: Ohh
19/01/25, 10:09 am - Subhojit: Amr kal dhuklo to
19/01/25, 10:35 am - ᗩʏᴏɴ ×͜×: Ou
19/01/25, 10:36 am - Subhojit: Ha
30/01/25, 1:02 pm - Subhojit: <Media omitted>
31/01/25, 10:29 pm - Subhojit: Bah bah
31/01/25, 10:30 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
24/02/25, 12:54 pm - Subhojit: Hi
24/02/25, 12:54 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
24/02/25, 12:55 pm - Subhojit: Ok
27/02/25, 11:35 am - ᗩʏᴏɴ ×͜×: <Media omitted>
27/02/25, 11:35 am - ᗩʏᴏɴ ×͜×: <Media omitted>
27/02/25, 11:35 am - ᗩʏᴏɴ ×͜×: <Media omitted>
27/02/25, 11:35 am - Subhojit: Ok ok
28/02/25, 10:18 pm - ᗩʏᴏɴ ×͜×: babu amar khata tomar kache?
28/02/25, 10:23 pm - Subhojit: ha
28/02/25, 10:23 pm - Subhojit: 🤣🤣🤣🤣🤣
02/03/25, 6:15 pm - ᗩʏᴏɴ ×͜×: Vai khata ta niechilam ami?
02/03/25, 6:16 pm - Subhojit: Na
02/03/25, 11:29 pm - ᗩʏᴏɴ ×͜×: Vai amar khatar pechone dekh mechanical ar recent hw lekha ache otar chobi ta patha naa
03/03/25, 12:25 am - Subhojit: Kal dichchi sokale
03/03/25, 9:06 am - ᗩʏᴏɴ ×͜×: Babu dao
03/03/25, 9:07 am - Subhojit: <Media omitted>
03/03/25, 9:07 am - Subhojit: <Media omitted>
03/03/25, 9:44 am - ᗩʏᴏɴ ×͜×: Next page a kichu chilo ba sure too?
03/03/25, 9:59 am - ᗩʏᴏɴ ×͜×: <Media omitted>
03/03/25, 7:49 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
03/03/25, 7:49 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
03/03/25, 11:54 pm - Subhojit: Porer ta ekechis?
03/03/25, 11:54 pm - Subhojit: De na bhai
04/03/25, 12:06 am - ᗩʏᴏɴ ×͜×: <Media omitted>
04/03/25, 12:06 am - ᗩʏᴏɴ ×͜×: <Media omitted>
04/03/25, 12:07 am - Subhojit: Ok
06/03/25, 5:46 pm - ᗩʏᴏɴ ×͜×: De vai🥺
06/03/25, 5:48 pm - Subhojit: null
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 5:48 pm - Subhojit: <Media omitted>
06/03/25, 6:01 pm - ᗩʏᴏɴ ×͜×: Sabas vai 🫦
09/03/25, 12:04 am - ᗩʏᴏɴ ×͜×: vai ajker math ar notes time pele pathie dis too
09/03/25, 12:05 am - Subhojit: Khata amr kache nei
09/03/25, 12:05 am - Subhojit: Sombar hobe
09/03/25, 12:05 am - Subhojit: College e
09/03/25, 12:05 am - ᗩʏᴏɴ ×͜×: <Media omitted>
11/03/25, 10:21 pm - ᗩʏᴏɴ ×͜×: Babu aj math hw ar 2nd question 140-200 heads ta solve kore dis too par6i na 🥺
11/03/25, 10:24 pm - Subhojit: Achchha korini
11/03/25, 10:24 pm - Subhojit: Korle debo
11/03/25, 10:50 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
11/03/25, 10:50 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
14/03/25, 8:25 am - Subhojit: Happy holi 🥳
14/03/25, 9:17 am - ᗩʏᴏɴ ×͜×: Happy holi💋
14/03/25, 9:19 am - Subhojit: 💦💦
15/03/25, 10:23 am - ᗩʏᴏɴ ×͜×: <Media omitted>
15/03/25, 10:28 pm - ᗩʏᴏɴ ×͜×: Vai sonibarer math gulo dis
15/03/25, 11:30 pm - Subhojit: Achchha
16/03/25, 7:18 am - ᗩʏᴏɴ ×͜×: De
16/03/25, 7:23 am - Subhojit: 8 tay dichchi
16/03/25, 7:56 am - Subhojit: <Media omitted>
16/03/25, 7:56 am - Subhojit: <Media omitted>
16/03/25, 8:14 am - ᗩʏᴏɴ ×͜×: 👍
21/03/25, 8:44 pm - Subhojit: A Sarcastic Tribute to Our Beloved Class Topper

Ladies and gentlemen,
Today, we gather here not to celebrate an ordinary student — oh no, that would be far too basic. We're here to bask in the divine glow of academic perfection. Yes, I’m talking about The Class Topper — the chosen one, the Einstein of our generation, the human version of a Google search engine… only with better handwriting.

Let us all take a moment to appreciate how effortlessly they breathe through exams while the rest of us are just trying to survive them. While we were busy making memories, this legend was busy making study timetables — color-coded, laminated, and probably alphabetized.

It’s incredible how they always seem to know what’s going to be on the test. Psychic powers? Maybe. Secret deal with the teacher? We’ll never know. But hey, who needs sleep, social life, or even sunshine, when you’ve got the joy of topping every single test?

And group projects? Ah yes. We just sit back and relax while they do all the work — and somehow thank us for participating. How thoughtful.

Let’s not forget how humble they are. After getting a 98, they go, “Ugh, I messed up so bad.” Meanwhile, the rest of us are over here celebrating our glorious 51 like we just won the Olympics.

So here’s to you, oh scholarly unicorn. May your GPA remain higher than our collective hopes and dreams. And may you never run out of pens, notes, or unsolicited advice.

Thank you, and please — teach us your ways. Or at least share your notes.
21/03/25, 8:53 pm - ᗩʏᴏɴ ×͜×: bara ata amake na Shreya ke patha bara
21/03/25, 8:53 pm - ᗩʏᴏɴ ×͜×: ami noob vai
21/03/25, 8:54 pm - Subhojit: Pro bhai 🫡🫡
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: <Media omitted>
21/03/25, 8:54 pm - Subhojit: A oi j nft otar withdraw bolchili... Otar ss
21/03/25, 8:55 pm - ᗩʏᴏɴ ×͜×: a66a i6aa hole bolbo toke
21/03/25, 8:55 pm - Subhojit: Hm
24/03/25, 9:12 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
24/03/25, 9:12 pm - Subhojit: Etai just?
24/03/25, 9:12 pm - ᗩʏᴏɴ ×͜×: Ha
24/03/25, 9:13 pm - Subhojit: Hm
25/03/25, 8:42 pm - Subhojit: null
31/03/25, 7:46 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
07/04/25, 9:13 pm - Subhojit: Aka hoyeche??😶
07/04/25, 9:13 pm - Subhojit: Pathiye dis to bhai
07/04/25, 9:13 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
07/04/25, 9:14 pm - Subhojit: Etai?
07/04/25, 9:14 pm - Subhojit: Ar kichu na?
07/04/25, 9:16 pm - ᗩʏᴏɴ ×͜×: Na
07/04/25, 9:27 pm - Subhojit: K
07/04/25, 9:27 pm - Subhojit: Ok
13/04/25, 5:20 pm - ᗩʏᴏɴ ×͜×: Vai tui bolli tor gen ai kora ache tahole tui amk team a nie kalker moddhe ppt submit korte parbi?
13/04/25, 11:14 pm - Subhojit: Amke kal sokale phn koris
13/04/25, 11:14 pm - Subhojit: Ba ami korbo
13/04/25, 11:14 pm - Subhojit: Mane ki hisab
13/04/25, 11:14 pm - Subhojit: Ki chai
13/04/25, 11:14 pm - Subhojit: Ektu kotha ache
13/04/25, 11:14 pm - Subhojit: Then kore debo
13/04/25, 11:15 pm - Subhojit: Mane ppt te kichu add korbo kina
13/04/25, 11:15 pm - Subhojit: Ba erom kichu
13/04/25, 11:20 pm - ᗩʏᴏɴ ×͜×: Ok
14/04/25, 9:41 am - ᗩʏᴏɴ ×͜×: Apex intelligence
14/04/25, 9:42 am - ᗩʏᴏɴ ×͜×: Generative AI for next Gen Mobility
14/04/25, 9:43 am - ᗩʏᴏɴ ×͜×: Byte me
14/04/25, 9:44 am - ᗩʏᴏɴ ×͜×: Ayon Sadhukhan
14/04/25, 9:47 am - ᗩʏᴏɴ ×͜×: <Media omitted>
14/04/25, 9:54 am - ᗩʏᴏɴ ×͜×: null
14/04/25, 9:54 am - ᗩʏᴏɴ ×͜×: <Media omitted>
14/04/25, 9:54 am - ᗩʏᴏɴ ×͜×: <Media omitted>
14/04/25, 9:56 am - Subhojit: Ektu black er modhdhe
14/04/25, 9:56 am - Subhojit: Ekta side e ektu besi jaga thakbe amn
14/04/25, 9:56 am - Subhojit: Mane white colour er font hole jni mise na jay
14/04/25, 9:56 am - Subhojit: Serom chaichi
14/04/25, 10:24 am - Subhojit: null
14/04/25, 10:31 am - Subhojit: <Media omitted>
14/04/25, 11:10 am - Subhojit: A tor figma er nijer banano kono project ache
14/04/25, 11:10 am - Subhojit: Ba ei event e jeta baniyechis seta de to
14/04/25, 11:24 am - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/NWPaO46GoQGmu2PMbZ19Jx/ROCK-PIRATES-_AKASH?node-id=0-1&t=Qqp5fkDiTjcZiqM0-1
14/04/25, 11:35 am - Subhojit: Tui uxplore korbi?
14/04/25, 11:35 am - Subhojit: Amader sathe???
14/04/25, 11:50 am - ᗩʏᴏɴ ×͜×: one piece evet ta ache too
14/04/25, 11:50 am - ᗩʏᴏɴ ×͜×: otar time ar sathe coincide korche uxplore
14/04/25, 11:50 am - Subhojit: Tui 2 to korte parbi
14/04/25, 11:50 am - ᗩʏᴏɴ ×͜×: ha
14/04/25, 11:50 am - Subhojit: Mane?
14/04/25, 11:51 am - Subhojit: Duto ak time e???
14/04/25, 11:51 am - ᗩʏᴏɴ ×͜×: kin2 one piece ar uxplore ar time ak
14/04/25, 11:51 am - Subhojit: Ki bolchis bara? 😶
14/04/25, 11:52 am - ᗩʏᴏɴ ×͜×: hm dekh akbar query  group a bolche 2 jon uxplore korbe ar 2 jon one piece korbe jodi time na change hoi
14/04/25, 11:52 am - Subhojit: Na na hobe na
14/04/25, 11:52 am - ᗩʏᴏɴ ×͜×: dara dekhe bolchi
14/04/25, 11:54 am - ᗩʏᴏɴ ×͜×: <Media omitted>
14/04/25, 11:55 am - ᗩʏᴏɴ ×͜×: Dekh explore ar half time one piece ar sathe ache
14/04/25, 1:57 pm - Subhojit: Korte parbi duto aksathe
14/04/25, 1:57 pm - Subhojit: No problem
14/04/25, 1:57 pm - Subhojit: J7ID6W6ABD -team code ..UXplore
14/04/25, 1:57 pm - Subhojit: Ene dhuke jas
14/04/25, 2:29 pm - ᗩʏᴏɴ ×͜×: ok
14/04/25, 2:29 pm - ᗩʏᴏɴ ×͜×: a66a ata only design korte hobe too
14/04/25, 2:29 pm - Subhojit: Yoooo
14/04/25, 2:29 pm - ᗩʏᴏɴ ×͜×: kk ache
14/04/25, 2:30 pm - Subhojit: Ami
14/04/25, 2:31 pm - Subhojit: Sohan
14/04/25, 2:31 pm - Subhojit: Rajdeep
14/04/25, 2:34 pm - ᗩʏᴏɴ ×͜×: a bara join hote par6i na
14/04/25, 2:34 pm - ᗩʏᴏɴ ×͜×: bolche already enrolled in one event
14/04/25, 2:35 pm - Subhojit: Wait
14/04/25, 2:36 pm - ᗩʏᴏɴ ×͜×: hm hoye ge66i
14/04/25, 2:36 pm - Subhojit: Ok
14/04/25, 10:33 pm - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/dwyCFUiU1hltGmiJfpNOW9/Untitled?node-id=3-2&t=tvm9tTnguRbdWnbn-1
14/04/25, 10:33 pm - ᗩʏᴏɴ ×͜×: VAI DEKHE BOLTO KAMON
14/04/25, 10:46 pm - Subhojit: Haa
14/04/25, 10:48 pm - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/dwyCFUiU1hltGmiJfpNOW9/Untitled?node-id=0-1&t=s407buUE0C4Y0wVK-1
14/04/25, 10:48 pm - ᗩʏᴏɴ ×͜×: ata dekh
14/04/25, 10:49 pm - Subhojit: Aki to
14/04/25, 10:49 pm - ᗩʏᴏɴ ×͜×: design alada
14/04/25, 10:50 pm - ᗩʏᴏɴ ×͜×: na aki ache
14/04/25, 10:50 pm - ᗩʏᴏɴ ×͜×: change korechilam
14/04/25, 10:50 pm - Subhojit: Ha setai to
14/04/25, 10:50 pm - Subhojit: Same e to dekhchi
14/04/25, 10:50 pm - ᗩʏᴏɴ ×͜×: hm
14/04/25, 11:06 pm - ᗩʏᴏɴ ×͜×: tor akta project pathas too dekhbo
14/04/25, 11:07 pm - Subhojit: Ok
14/04/25, 11:07 pm - Subhojit: Okhane jeta baniyechi setai dichhci
14/04/25, 11:07 pm - Subhojit: Dara
14/04/25, 11:19 pm - Subhojit: https://www.figma.com/proto/ElZk5mAN0oWNGVqxmXSYy0
14/04/25, 11:21 pm - Subhojit: Prototyping ta dekhli? <This message was edited>
14/04/25, 11:42 pm - ᗩʏᴏɴ ×͜×: bhai req accept kor
14/04/25, 11:42 pm - ᗩʏᴏɴ ×͜×: dekh bo
14/04/25, 11:43 pm - Subhojit: Hm
14/04/25, 11:45 pm - ᗩʏᴏɴ ×͜×: hm prototyping ta valo hoyeche
14/04/25, 11:45 pm - Subhojit: Achchha😭😭😶
14/04/25, 11:45 pm - ᗩʏᴏɴ ×͜×: vai ami kon jaigata korbo bolis ..  login page .  body . nki ending page .. sei moto practice korbo
14/04/25, 11:46 pm - Subhojit: Login page ar best best pic collection... Mane dhor kono pic er dorkar...like book ba cars... Tale peye jbo tor theke
14/04/25, 11:47 pm - Subhojit: Login ar ending page ta e kor...
14/04/25, 11:48 pm - ᗩʏᴏɴ ×͜×: <Media omitted>
18/04/25, 10:34 pm - Subhojit: This message was deleted
18/04/25, 10:34 pm - Subhojit: This message was deleted
18/04/25, 10:35 pm - Subhojit: This message was deleted
18/04/25, 11:33 pm - Subhojit: https://www.figma.com/proto/ElZk5mAN0oWNGVqxmXSYy0/Untitled?page-id=0%3A1&node-id=149-115&p=f&viewport=1446%2C227%2C0.06&t=HKksQbHAT703SSl3-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=149%3A115
18/04/25, 11:41 pm - Subhojit: Cholbe eta???
18/04/25, 11:42 pm - Subhojit: Ektu animation edik odik ache... Ota kore nebo thik
18/04/25, 11:42 pm - Subhojit: Tale uxplore e eta e dhukiye debo
18/04/25, 11:54 pm - ᗩʏᴏɴ ×͜×: animatio thik aache but color combination ta na thik lagche na bohut chokehe lagche aktu soothing ar light color ar moddhe kor like white  ba amon kichu
19/04/25, 12:47 am - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/H14xWn2WMZM4ADaGvNmAP3/Untitled?node-id=0-1&t=MThHYFXQJBvHm3KA-1.
19/04/25, 12:47 am - ᗩʏᴏɴ ×͜×: dekhe bolis too akmon hoyeche
19/04/25, 8:34 am - Subhojit: Bhalo bhai
19/04/25, 12:05 pm - ᗩʏᴏɴ ×͜×: Hacker4bengal a name diechis too
19/04/25, 12:41 pm - Subhojit: Ki jni
19/04/25, 12:41 pm - Subhojit: Jni na🤣🤣
19/04/25, 12:42 pm - ᗩʏᴏɴ ×͜×: <Media omitted>

In [5]:
pattern = r'\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s(?:am|pm)'

In [6]:
messages=re.split(pattern,data)[1:]
len(messages)
messages

[' - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 ' - ᗩʏᴏɴ ×͜×: Vai tui svmcm ar print out college a joma diechilis?\n',
 ' - Subhojit: Gechilam\n',
 ' - Subhojit: Joma nayni\n',
 ' - Subhojit: Tor dhukeche???\n',
 ' - ᗩʏᴏɴ ×͜×: Na vai\n',
 ' - Subhojit: Ohh\n',
 ' - Subhojit: Amr kal dhuklo to\n',
 ' - ᗩʏᴏɴ ×͜×: Ou\n',
 ' - Subhojit: Ha\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: Bah bah\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Hi\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Ok\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Ok ok\n',
 ' - ᗩʏᴏɴ ×͜×: babu amar khata tomar kache?\n',
 ' - Subhojit: ha\n',
 ' - Subhojit: 🤣🤣🤣🤣🤣\n',
 ' - ᗩʏᴏɴ ×͜×: Vai khata ta niechilam ami?\n',
 ' - Subhojit: Na\n',
 ' - ᗩʏᴏɴ ×͜×: Vai amar khatar pechone dekh mechanical ar recent hw lekha ache otar chobi ta patha naa\n',
 ' - Subhojit: Kal dichchi sokale\n',
 ' - ᗩʏᴏɴ ×͜×: Babu dao\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: Next page a kichu chilo ba sure too?\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Porer ta ekechis?\n',
 ' - Subhojit: De na bhai\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Ok\n',
 ' - ᗩʏᴏɴ ×͜×: De vai🥺\n',
 ' - Subhojit: null\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: Sabas vai 🫦\n',
 ' - ᗩʏᴏɴ ×͜×: vai ajker math ar notes time pele pathie dis too\n',
 ' - Subhojit: Khata amr kache nei\n',
 ' - Subhojit: Sombar hobe\n',
 ' - Subhojit: College e\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: Babu aj math hw ar 2nd question 140-200 heads ta solve kore dis too par6i na 🥺\n',
 ' - Subhojit: Achchha korini\n',
 ' - Subhojit: Korle debo\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Happy holi 🥳\n',
 ' - ᗩʏᴏɴ ×͜×: Happy holi💋\n',
 ' - Subhojit: 💦💦\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: Vai sonibarer math gulo dis\n',
 ' - Subhojit: Achchha\n',
 ' - ᗩʏᴏɴ ×͜×: De\n',
 ' - Subhojit: 8 tay dichchi\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: 👍\n',
 " - Subhojit: A Sarcastic Tribute to Our Beloved Class Topper\n\nLadies and gentlemen,\nToday, we gather here not to celebrate an ordinary student — oh no, that would be far too basic. We're here to bask in the divine glow of academic perfection. Yes, I’m talking about The Class Topper — the chosen one, the Einstein of our generation, the human version of a Google search engine… only with better handwriting.\n\nLet us all take a moment to appreciate how effortlessly they breathe through exams while the rest of us are just trying to survive them. While we were busy making memories, this legend was busy making study timetables — color-coded, laminated, and probably alphabetized.\n\nIt’s incredible how they always seem to know what’s going to be on the test. Psychic powers? Maybe. Secret deal with the teacher? We’ll never know. But hey, who needs sleep, social life, or even sunshine, when you’ve got the joy of topping every single test?\n\nAnd group projects? Ah yes. We just sit back and relax while they do all the work — and somehow thank us for participating. How thoughtful.\n\nLet’s not forget how humble they are. After getting a 98, they go, “Ugh, I messed up so bad.” Meanwhile, the rest of us are over here celebrating our glorious 51 like we just won the Olympics.\n\nSo here’s to you, oh scholarly unicorn. May your GPA remain higher than our collective hopes and dreams. And may you never run out of pens, notes, or unsolicited advice.\n\nThank you, and please — teach us your ways. Or at least share your notes.\n",
 ' - ᗩʏᴏɴ ×͜×: bara ata amake na Shreya ke patha bara\n',
 ' - ᗩʏᴏɴ ×͜×: ami noob vai\n',
 ' - Subhojit: Pro bhai 🫡🫡\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: A oi j nft otar withdraw bolchili... Otar ss\n',
 ' - ᗩʏᴏɴ ×͜×: a66a i6aa hole bolbo toke\n',
 ' - Subhojit: Hm\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Etai just?\n',
 ' - ᗩʏᴏɴ ×͜×: Ha\n',
 ' - Subhojit: Hm\n',
 ' - Subhojit: null\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Aka hoyeche??😶\n',
 ' - Subhojit: Pathiye dis to bhai\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Etai?\n',
 ' - Subhojit: Ar kichu na?\n',
 ' - ᗩʏᴏɴ ×͜×: Na\n',
 ' - Subhojit: K\n',
 ' - Subhojit: Ok\n',
 ' - ᗩʏᴏɴ ×͜×: Vai tui bolli tor gen ai kora ache tahole tui amk team a nie kalker moddhe ppt submit korte parbi?\n',
 ' - Subhojit: Amke kal sokale phn koris\n',
 ' - Subhojit: Ba ami korbo\n',
 ' - Subhojit: Mane ki hisab\n',
 ' - Subhojit: Ki chai\n',
 ' - Subhojit: Ektu kotha ache\n',
 ' - Subhojit: Then kore debo\n',
 ' - Subhojit: Mane ppt te kichu add korbo kina\n',
 ' - Subhojit: Ba erom kichu\n',
 ' - ᗩʏᴏɴ ×͜×: Ok\n',
 ' - ᗩʏᴏɴ ×͜×: Apex intelligence\n',
 ' - ᗩʏᴏɴ ×͜×: Generative AI for next Gen Mobility\n',
 ' - ᗩʏᴏɴ ×͜×: Byte me\n',
 ' - ᗩʏᴏɴ ×͜×: Ayon Sadhukhan\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: null\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: Ektu black er modhdhe\n',
 ' - Subhojit: Ekta side e ektu besi jaga thakbe amn\n',
 ' - Subhojit: Mane white colour er font hole jni mise na jay\n',
 ' - Subhojit: Serom chaichi\n',
 ' - Subhojit: null\n',
 ' - Subhojit: <Media omitted>\n',
 ' - Subhojit: A tor figma er nijer banano kono project ache\n',
 ' - Subhojit: Ba ei event e jeta baniyechis seta de to\n',
 ' - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/NWPaO46GoQGmu2PMbZ19Jx/ROCK-PIRATES-_AKASH?node-id=0-1&t=Qqp5fkDiTjcZiqM0-1\n',
 ' - Subhojit: Tui uxplore korbi?\n',
 ' - Subhojit: Amader sathe???\n',
 ' - ᗩʏᴏɴ ×͜×: one piece evet ta ache too\n',
 ' - ᗩʏᴏɴ ×͜×: otar time ar sathe coincide korche uxplore\n',
 ' - Subhojit: Tui 2 to korte parbi\n',
 ' - ᗩʏᴏɴ ×͜×: ha\n',
 ' - Subhojit: Mane?\n',
 ' - Subhojit: Duto ak time e???\n',
 ' - ᗩʏᴏɴ ×͜×: kin2 one piece ar uxplore ar time ak\n',
 ' - Subhojit: Ki bolchis bara? 😶\n',
 ' - ᗩʏᴏɴ ×͜×: hm dekh akbar query  group a bolche 2 jon uxplore korbe ar 2 jon one piece korbe jodi time na change hoi\n',
 ' - Subhojit: Na na hobe na\n',
 ' - ᗩʏᴏɴ ×͜×: dara dekhe bolchi\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - ᗩʏᴏɴ ×͜×: Dekh explore ar half time one piece ar sathe ache\n',
 ' - Subhojit: Korte parbi duto aksathe\n',
 ' - Subhojit: No problem\n',
 ' - Subhojit: J7ID6W6ABD -team code ..UXplore\n',
 ' - Subhojit: Ene dhuke jas\n',
 ' - ᗩʏᴏɴ ×͜×: ok\n',
 ' - ᗩʏᴏɴ ×͜×: a66a ata only design korte hobe too\n',
 ' - Subhojit: Yoooo\n',
 ' - ᗩʏᴏɴ ×͜×: kk ache\n',
 ' - Subhojit: Ami\n',
 ' - Subhojit: Sohan\n',
 ' - Subhojit: Rajdeep\n',
 ' - ᗩʏᴏɴ ×͜×: a bara join hote par6i na\n',
 ' - ᗩʏᴏɴ ×͜×: bolche already enrolled in one event\n',
 ' - Subhojit: Wait\n',
 ' - ᗩʏᴏɴ ×͜×: hm hoye ge66i\n',
 ' - Subhojit: Ok\n',
 ' - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/dwyCFUiU1hltGmiJfpNOW9/Untitled?node-id=3-2&t=tvm9tTnguRbdWnbn-1\n',
 ' - ᗩʏᴏɴ ×͜×: VAI DEKHE BOLTO KAMON\n',
 ' - Subhojit: Haa\n',
 ' - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/dwyCFUiU1hltGmiJfpNOW9/Untitled?node-id=0-1&t=s407buUE0C4Y0wVK-1\n',
 ' - ᗩʏᴏɴ ×͜×: ata dekh\n',
 ' - Subhojit: Aki to\n',
 ' - ᗩʏᴏɴ ×͜×: design alada\n',
 ' - ᗩʏᴏɴ ×͜×: na aki ache\n',
 ' - ᗩʏᴏɴ ×͜×: change korechilam\n',
 ' - Subhojit: Ha setai to\n',
 ' - Subhojit: Same e to dekhchi\n',
 ' - ᗩʏᴏɴ ×͜×: hm\n',
 ' - ᗩʏᴏɴ ×͜×: tor akta project pathas too dekhbo\n',
 ' - Subhojit: Ok\n',
 ' - Subhojit: Okhane jeta baniyechi setai dichhci\n',
 ' - Subhojit: Dara\n',
 ' - Subhojit: https://www.figma.com/proto/ElZk5mAN0oWNGVqxmXSYy0\n',
 ' - Subhojit: Prototyping ta dekhli? <This message was edited>\n',
 ' - ᗩʏᴏɴ ×͜×: bhai req accept kor\n',
 ' - ᗩʏᴏɴ ×͜×: dekh bo\n',
 ' - Subhojit: Hm\n',
 ' - ᗩʏᴏɴ ×͜×: hm prototyping ta valo hoyeche\n',
 ' - Subhojit: Achchha😭😭😶\n',
 ' - ᗩʏᴏɴ ×͜×: vai ami kon jaigata korbo bolis ..  login page .  body . nki ending page .. sei moto practice korbo\n',
 ' - Subhojit: Login page ar best best pic collection... Mane dhor kono pic er dorkar...like book ba cars... Tale peye jbo tor theke\n',
 ' - Subhojit: Login ar ending page ta e kor...\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n',
 ' - Subhojit: This message was deleted\n',
 ' - Subhojit: This message was deleted\n',
 ' - Subhojit: This message was deleted\n',
 ' - Subhojit: https://www.figma.com/proto/ElZk5mAN0oWNGVqxmXSYy0/Untitled?page-id=0%3A1&node-id=149-115&p=f&viewport=1446%2C227%2C0.06&t=HKksQbHAT703SSl3-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=149%3A115\n',
 ' - Subhojit: Cholbe eta???\n',
 ' - Subhojit: Ektu animation edik odik ache... Ota kore nebo thik\n',
 ' - Subhojit: Tale uxplore e eta e dhukiye debo\n',
 ' - ᗩʏᴏɴ ×͜×: animatio thik aache but color combination ta na thik lagche na bohut chokehe lagche aktu soothing ar light color ar moddhe kor like white  ba amon kichu\n',
 ' - ᗩʏᴏɴ ×͜×: https://www.figma.com/design/H14xWn2WMZM4ADaGvNmAP3/Untitled?node-id=0-1&t=MThHYFXQJBvHm3KA-1.\n',
 ' - ᗩʏᴏɴ ×͜×: dekhe bolis too akmon hoyeche\n',
 ' - Subhojit: Bhalo bhai\n',
 ' - ᗩʏᴏɴ ×͜×: Hacker4bengal a name diechis too\n',
 ' - Subhojit: Ki jni\n',
 ' - Subhojit: Jni na🤣🤣\n',
 ' - ᗩʏᴏɴ ×͜×: <Media omitted>\n']

In [7]:
dates=re.findall(pattern,data)
new_date=[]
for date in dates:
    new_date.append(date.replace('\u202f',' '))
new_date

['01/01/25, 7:07 pm',
 '19/01/25, 8:58 am',
 '19/01/25, 9:28 am',
 '19/01/25, 9:28 am',
 '19/01/25, 9:28 am',
 '19/01/25, 9:28 am',
 '19/01/25, 10:09 am',
 '19/01/25, 10:09 am',
 '19/01/25, 10:35 am',
 '19/01/25, 10:36 am',
 '30/01/25, 1:02 pm',
 '31/01/25, 10:29 pm',
 '31/01/25, 10:30 pm',
 '24/02/25, 12:54 pm',
 '24/02/25, 12:54 pm',
 '24/02/25, 12:55 pm',
 '27/02/25, 11:35 am',
 '27/02/25, 11:35 am',
 '27/02/25, 11:35 am',
 '27/02/25, 11:35 am',
 '28/02/25, 10:18 pm',
 '28/02/25, 10:23 pm',
 '28/02/25, 10:23 pm',
 '02/03/25, 6:15 pm',
 '02/03/25, 6:16 pm',
 '02/03/25, 11:29 pm',
 '03/03/25, 12:25 am',
 '03/03/25, 9:06 am',
 '03/03/25, 9:07 am',
 '03/03/25, 9:07 am',
 '03/03/25, 9:44 am',
 '03/03/25, 9:59 am',
 '03/03/25, 7:49 pm',
 '03/03/25, 7:49 pm',
 '03/03/25, 11:54 pm',
 '03/03/25, 11:54 pm',
 '04/03/25, 12:06 am',
 '04/03/25, 12:06 am',
 '04/03/25, 12:07 am',
 '06/03/25, 5:46 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 5:48 pm',
 '06/03/25, 6:01 pm',
 '09/03/25, 12:04 am',
 '09/03/25, 12:05 am',
 '09/03/25, 12:05 am',
 '09/03/25, 12:05 am',
 '09/03/25, 12:05 am',
 '11/03/25, 10:21 pm',
 '11/03/25, 10:24 pm',
 '11/03/25, 10:24 pm',
 '11/03/25, 10:50 pm',
 '11/03/25, 10:50 pm',
 '14/03/25, 8:25 am',
 '14/03/25, 9:17 am',
 '14/03/25, 9:19 am',
 '15/03/25, 10:23 am',
 '15/03/25, 10:28 pm',
 '15/03/25, 11:30 pm',
 '16/03/25, 7:18 am',
 '16/03/25, 7:23 am',
 '16/03/25, 7:56 am',
 '16/03/25, 7:56 am',
 '16/03/25, 8:14 am',
 '21/03/25, 8:44 pm',
 '21/03/25, 8:53 pm',
 '21/03/25, 8:53 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:54 pm',
 '21/03/25, 8:55 pm',
 '21/03/25, 8:55 pm',
 '24/03/25, 9:12 pm',
 '24/03/25, 9:12 pm',
 '24/03/25, 9:12 pm',
 '24/03/25, 9:13 pm',
 '25/03/25, 8:42 pm',
 '31/03/25, 7:46 pm',
 '07/04/25, 9:13 pm',
 '07/04/25, 9:13 pm',
 '07/04/25, 9:13 pm',
 '07/04/25, 9:14 pm',
 '07/04/25, 9:14 pm',
 '07/04/25, 9:16 pm',
 '07/04/25, 9:27 pm',
 '07/04/25, 9:27 pm',
 '13/04/25, 5:20 pm',
 '13/04/25, 11:14 pm',
 '13/04/25, 11:14 pm',
 '13/04/25, 11:14 pm',
 '13/04/25, 11:14 pm',
 '13/04/25, 11:14 pm',
 '13/04/25, 11:14 pm',
 '13/04/25, 11:15 pm',
 '13/04/25, 11:15 pm',
 '13/04/25, 11:20 pm',
 '14/04/25, 9:41 am',
 '14/04/25, 9:42 am',
 '14/04/25, 9:43 am',
 '14/04/25, 9:44 am',
 '14/04/25, 9:47 am',
 '14/04/25, 9:54 am',
 '14/04/25, 9:54 am',
 '14/04/25, 9:54 am',
 '14/04/25, 9:56 am',
 '14/04/25, 9:56 am',
 '14/04/25, 9:56 am',
 '14/04/25, 9:56 am',
 '14/04/25, 10:24 am',
 '14/04/25, 10:31 am',
 '14/04/25, 11:10 am',
 '14/04/25, 11:10 am',
 '14/04/25, 11:24 am',
 '14/04/25, 11:35 am',
 '14/04/25, 11:35 am',
 '14/04/25, 11:50 am',
 '14/04/25, 11:50 am',
 '14/04/25, 11:50 am',
 '14/04/25, 11:50 am',
 '14/04/25, 11:50 am',
 '14/04/25, 11:51 am',
 '14/04/25, 11:51 am',
 '14/04/25, 11:51 am',
 '14/04/25, 11:52 am',
 '14/04/25, 11:52 am',
 '14/04/25, 11:52 am',
 '14/04/25, 11:54 am',
 '14/04/25, 11:55 am',
 '14/04/25, 1:57 pm',
 '14/04/25, 1:57 pm',
 '14/04/25, 1:57 pm',
 '14/04/25, 1:57 pm',
 '14/04/25, 2:29 pm',
 '14/04/25, 2:29 pm',
 '14/04/25, 2:29 pm',
 '14/04/25, 2:29 pm',
 '14/04/25, 2:30 pm',
 '14/04/25, 2:31 pm',
 '14/04/25, 2:31 pm',
 '14/04/25, 2:34 pm',
 '14/04/25, 2:34 pm',
 '14/04/25, 2:35 pm',
 '14/04/25, 2:36 pm',
 '14/04/25, 2:36 pm',
 '14/04/25, 10:33 pm',
 '14/04/25, 10:33 pm',
 '14/04/25, 10:46 pm',
 '14/04/25, 10:48 pm',
 '14/04/25, 10:48 pm',
 '14/04/25, 10:49 pm',
 '14/04/25, 10:49 pm',
 '14/04/25, 10:50 pm',
 '14/04/25, 10:50 pm',
 '14/04/25, 10:50 pm',
 '14/04/25, 10:50 pm',
 '14/04/25, 10:50 pm',
 '14/04/25, 11:06 pm',
 '14/04/25, 11:07 pm',
 '14/04/25, 11:07 pm',
 '14/04/25, 11:07 pm',
 '14/04/25, 11:19 pm',
 '14/04/25, 11:21 pm',
 '14/04/25, 11:42 pm',
 '14/04/25, 11:42 pm',
 '14/04/25, 11:43 pm',
 '14/04/25, 11:45 pm',
 '14/04/25, 11:45 pm',
 '14/04/25, 11:45 pm',
 '14/04/25, 11:46 pm',
 '14/04/25, 11:47 pm',
 '14/04/25, 11:48 pm',
 '18/04/25, 10:34 pm',
 '18/04/25, 10:34 pm',
 '18/04/25, 10:35 pm',
 '18/04/25, 11:33 pm',
 '18/04/25, 11:41 pm',
 '18/04/25, 11:42 pm',
 '18/04/25, 11:42 pm',
 '18/04/25, 11:54 pm',
 '19/04/25, 12:47 am',
 '19/04/25, 12:47 am',
 '19/04/25, 8:34 am',
 '19/04/25, 12:05 pm',
 '19/04/25, 12:41 pm',
 '19/04/25, 12:41 pm',
 '19/04/25, 12:42 pm']

In [8]:
df=pd.DataFrame({"user_message" : messages, "message_date" : dates})
#convert message data type
df["message_date"]=pd.to_datetime(df["message_date"],format="%d/%m/%y, %I:%M %p")

df.rename(columns={"message_date" : "date"},inplace=True)

df.head()

                                        user_message                date
0   - Messages and calls are end-to-end encrypted... 2025-01-01 19:07:00
1   - ᗩʏᴏɴ ×͜×: Vai tui svmcm ar print out colleg... 2025-01-19 08:58:00
2                             - Subhojit: Gechilam\n 2025-01-19 09:28:00
3                           - Subhojit: Joma nayni\n 2025-01-19 09:28:00
4                      - Subhojit: Tor dhukeche???\n 2025-01-19 09:28:00

In [9]:
df.shape

(204, 2)

In [10]:
users=[]
messages=[]
for message in df["user_message"]:
    entry = re.split(r"([\w\W]+?):\s", message)
    if entry[1:]: #user name
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append("WhatsApp_Notification")
        messages.append(entry[0])
df["user"]=users
df["message"]=messages
df.drop(columns=["user_message"], inplace=True)
df.head(10)

,date,user,message
0,2025-01-01 19:07:00,WhatsApp_Notification,- Messages and calls are end-to-end encrypted...
1,2025-01-19 08:58:00,- ᗩʏᴏɴ ×͜×,Vai tui svmcm ar print out college a joma diec...
2,2025-01-19 09:28:00,- Subhojit,Gechilam\n
3,2025-01-19 09:28:00,- Subhojit,Joma nayni\n
4,2025-01-19 09:28:00,- Subhojit,Tor dhukeche???\n
5,2025-01-19 09:28:00,- ᗩʏᴏɴ ×͜×,Na vai\n
6,2025-01-19 10:09:00,- Subhojit,Ohh\n
7,2025-01-19 10:09:00,- Subhojit,Amr kal dhuklo to\n
8,2025-01-19 10:35:00,- ᗩʏᴏɴ ×͜×,Ou\n
9,2025-01-19 10:36:00,- Subhojit,Ha\n

In [11]:
df["year"]=df["date"].dt.year

In [12]:
df.head()

,date,user,message,year
0,2025-01-01 19:07:00,WhatsApp_Notification,- Messages and calls are end-to-end encrypted...,2025
1,2025-01-19 08:58:00,- ᗩʏᴏɴ ×͜×,Vai tui svmcm ar print out college a joma diec...,2025
2,2025-01-19 09:28:00,- Subhojit,Gechilam\n,2025
3,2025-01-19 09:28:00,- Subhojit,Joma nayni\n,2025
4,2025-01-19 09:28:00,- Subhojit,Tor dhukeche???\n,2025

In [13]:
df["month"]=df["date"].dt.month_name()

In [14]:
df.head()

,date,user,message,year,month
0,2025-01-01 19:07:00,WhatsApp_Notification,- Messages and calls are end-to-end encrypted...,2025,January
1,2025-01-19 08:58:00,- ᗩʏᴏɴ ×͜×,Vai tui svmcm ar print out college a joma diec...,2025,January
2,2025-01-19 09:28:00,- Subhojit,Gechilam\n,2025,January
3,2025-01-19 09:28:00,- Subhojit,Joma nayni\n,2025,January
4,2025-01-19 09:28:00,- Subhojit,Tor dhukeche???\n,2025,January

In [15]:
df["day"]=df["date"].dt.day

In [16]:
df["hour"]=df["date"].dt.hour
df["minute"]=df["date"].dt.minute
df["second"]=df["date"].dt.second

In [17]:
df.head()

,date,user,message,year,month,day,hour,minute,second
0,2025-01-01 19:07:00,WhatsApp_Notification,- Messages and calls are end-to-end encrypted...,2025,January,1,19,7,0
1,2025-01-19 08:58:00,- ᗩʏᴏɴ ×͜×,Vai tui svmcm ar print out college a joma diec...,2025,January,19,8,58,0
2,2025-01-19 09:28:00,- Subhojit,Gechilam\n,2025,January,19,9,28,0
3,2025-01-19 09:28:00,- Subhojit,Joma nayni\n,2025,January,19,9,28,0
4,2025-01-19 09:28:00,- Subhojit,Tor dhukeche???\n,2025,January,19,9,28,0

In [18]:
new_df=df[df["user"].str.contains(selected, case=False, na=False)]

NameError: name 'selected' is not defined

In [ ]:
words=[]
for message in new_df["message"]:
    words.extend(message.split())

In [ ]:
len(words)

In [ ]:
pip install urlextract

In [ ]:
pip install extractor

In [ ]:
from urlextract import URLExtract
extractor=URLExtract()
links=[]
for message in df["message"]:
    links.extend(extractor.find_urls(message))

In [ ]:
links

In [ ]:
len(links)

In [ ]:
df

In [ ]:
x=df["user"].value_counts().head(5)

In [ ]:
import matplotlib.pyplot as plt
name=x.index
count=x.values
plt.bar(name,count)
plt.xticks(rotation=50)
plt.show()

In [ ]:
per=round((df["user"].value_counts()/df.shape[0])*100).reset_index().rename(columns={"user":"name","count":"percent"})

In [ ]:
per

In [ ]:
per.index= range(1, len(per) + 1)

In [ ]:
per

In [ ]:
words=[]
for message in df["message"]:
    words.extend(message.split())

In [ ]:
words

In [28]:
from collections import Counter
pd.DataFrame(Counter(words).most_common(20))

           0   1
0     <media  49
1   omitted>  49
2         ar  15
3         na  15
4        vai  11
5         ok   9
6         ta   9
7       ache   8
8          e   7
9         hm   7
10       one   6
11        ba   6
12      time   6
13       tui   5
14       tor   5
15        ha   5
16      dekh   5
17      page   5
18     kichu   5
19      bhai   5

In [55]:
new_df = df[~df["user"].str.contains("group_notification", case=False, na=False)]

In [56]:
# new_df=df[~df["user"].str.contains("group_notification", case=False, na=False)]

In [57]:
new_df=new_df[~new_df["user"].str.contains("WhatsApp_Notification", case=False, na=False)]

In [58]:
new_df=new_df[~new_df["message"].str.contains("<Media omitted>", case=False, na=False)]

In [59]:
import nltk
from nltk.corpus import stopwords
stop_words=[]
nltk.download('stopwords')
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ayon\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [60]:
stop_words

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [61]:
words=[]
for message in new_df["message"]:
    for word in message.lower().split():
        if word not in stop_words:
            words.append(word)
from collections import Counter
pd.DataFrame(Counter(words).most_common(20))

          0   1
0        ar  15
1        na  15
2       vai  11
3        ok   9
4        ta   9
5      ache   8
6         e   7
7        hm   7
8        ba   6
9      time   6
10      tui   5
11      tor   5
12       ha   5
13     dekh   5
14     page   5
15    kichu   5
16     bhai   5
17        —   5
18       us   5
19  uxplore   5

In [62]:
pip install emoji

Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ---------------------------------------- 0.0/590.6 kB ? eta -:--:--
   ----------------------------------- ---- 524.3/590.6 kB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 590.6/590.6 kB 2.1 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1
Note: you may need to restart the kernel to use updated packages.

In [63]:
import emoji

In [65]:
emojis=[]
for message in df["message"]:
    emojis.extend([ c for c in message if c in emoji.EMOJI_DATA])
pd.DataFrame(Counter(emojis).most_common(len(Counter(emojis))))

   0  1
0  🤣  7
1  😶  3
2  🥺  2
3  💦  2
4  🫡  2
5  😭  2
6  🫦  1
7  🥳  1
8  💋  1
9  👍  1